### ISSUE TITLE
The result achieved is wrong

### ISSUE THREAD

**Issue by yuancaimaiyi** [rajkataria/ReliableResectioning#3]
@rajkataria 
Hi ,After reading your paper, I thought the effect was great, so I implemented it, but the original method of colmap based on the best view selection based on the pyramid score is the right result, and your MDS method is wrong.
COLMAP  pyramid score
![MIN_UNCERTAINTY](https://user-images.githubusercontent.com/28293910/131995306-339b44ff-2a03-4b26-8b99-abb8e6d10922.png)
MDS （yours)
![mds](https://user-images.githubusercontent.com/28293910/131995340-38fc7d43-729b-4e30-adc5-d30f1913047c.png)

**Comment by rajkataria** [comment]
Hi @yuancaimaiyi,

There can be several reasons why the result can be incorrect. 

(1) Your implementation may not match ours. Have you run the datasets presented in our paper on your implementation? Did you get the same result as us? If not, then your implementation may differ from ours. We have integrated our method into COLMAP (and OpenSfM). You can just use our implementation to see how our method performs on your dataset.

(2) We did notice in some seldom cases that correct reconstructions turned into failures when using our method. These cases are rare and the opposite is true most of the time (as presented in our results). Rarely does a  method improve on baselines in every single case. 

Instead of trying to debug your implementation, you can just download ours and see how it performs on your datasets.

Thanks,
Raj

**Comment by yuancaimaiyi** [comment]
@rajkataria 
Thank you very much for your advice, I think I might be wrong, I will check again. In addition, when I saw the paper, I thought it was amazing, thank you very much for your work

**Comment by rajkataria** [comment]
No problem.

**Comment by lxxue** [comment]
Hi Raj,

Thanks for sharing the code. I tried your implementation in colmap-3.4 with minimal changes for [compatibility](https://github.com/lxxue/ReliableResectioning/commit/5a3ead92d74102ca3353d546d9d761a2c88a0a05) with ceres 2.0. I use this command to get the sparse reconstructions on several Duplicate structure datasets like `street`:
`colmap automatic_reconstructor  --workspace_path ${workspace_path}   --image_path ${image_path}   --dense 0   --use_gpu 0`
(didn't use SIFTGPU due to some problems similar to [this](https://github.com/colmap/colmap/issues/627#issuecomment-502170324))

The reconstruction on the `street` dataset is like this:
![street](https://user-images.githubusercontent.com/22346567/132538166-f928411b-71cd-4022-b87d-2ca4db8d7dd4.png)

I wonder if you have any idea where the problem could be?

**Comment by rajkataria** [comment]
Hi Lixin,

I vaguely remember having to run the pipeline step by step. I'm not sure if automatic_reconstructor requires separate instantiation of our code. If you a put a print statement around **line 145 in src/controllers/incremental_mapper.cc** does it show up when running the code? This is where we instantiate our method - `MDS mds = MDS(database_path, "AAM", &database_cache_);`

Do other scenes from the same dataset, like books, cereal, or desk also fail?
If this is the case and our code is being instantiated (verified using a print statement), then we would need to dig further. In our experiments we only used SIFT along with vocab tree matching.

**Comment by lxxue** [comment]
Hi Raj,

Thanks for the quick reply. Indeed `automatic_reconstructor` is different as it uses an exhaustive matcher instead of a vocabulary tree matcher. Then I ran the pipeline step by step using a [vocabulary tree](https://demuc.de/colmap/vocab_tree_flickr100K_words32K.bin) with 32k visual words from colmap's author. Here is the printed message so I guess your method is running:
![info](https://user-images.githubusercontent.com/22346567/132741872-61c8ad90-1018-44a0-86c5-3fca624555bb.png)

However, the result is still wrong on all these small datasets, e.g. `cereal` here:
![cereal](https://user-images.githubusercontent.com/22346567/132742154-e5d371b6-a9ed-46b4-b769-cd3c9f994cd7.png)

**Comment by rajkataria** [comment]
Hi Lixin,

I reproduced the environment on my end (required ceres-solver-1.14.0) and I believe I may have stumbled across an issue (not in our repo). I was having trouble reproducing our successful result, but everything seemed to work when I started the dataset evaluation from scratch (I removed the sparse outputs and the database.db files).

```
export dataset=$1
export COLMAP_HOME=$2
export VOCAB_TREE_PATH=$3

rm -R $dataset/database.db $dataset/sparse $dataset/sparse_converted
mkdir $dataset/sparse && mkdir $dataset/sparse_converted

$COLMAP_HOME/colmap feature_extractor --image_path $dataset/images/ --database_path $dataset/database.db

$COLMAP_HOME/colmap exhaustive_matcher --database_path $dataset/database.db
#$COLMAP_HOME/colmap vocab_tree_matcher --database_path $dataset/database.db --VocabTreeMatching.vocab_tree_path $VOCAB_TREE_PATH/vocab_tree_flickr100K_words32K.bin

$COLMAP_HOME/colmap mapper --database_path $dataset/database.db --image_path $dataset/images/ --export_path $dataset/sparse/

$COLMAP_HOME/colmap model_converter --input_path $dataset/sparse/0/ --output_path $dataset/sparse_converted/colmap-output.ply --output_type ply
$COLMAP_HOME/colmap model_converter --input_path $dataset/sparse/0/ --output_path $dataset/sparse_converted/colmap-output.nvm --output_type nvm
```

Let me know if this works for you. I got it working on the street and books scene.

Thanks,
Raj

**Comment by lxxue** [comment]
Hi Raj,

Thanks for the script. I installed ceres-solver-1.14.0 and build the colmap-3.4 without modifying anything. I used the following script to run the experiments from scratch:

```
mkdir ${results}/${dset}
${colmap} \
  feature_extractor \
  --database_path ${results}/${dset}/database.db \
  --image_path ${datasets}/${dset}/ \
  --SiftExtraction.use_gpu 0
${colmap} \
  exhaustive_matcher \
  --database_path ${results}/${dset}/database.db \
  --SiftMatching.use_gpu 0
${colmap} \
  vocab_tree_matcher \
  --database_path ${results}/${dset}/database.db \
  --VocabTreeMatching.vocab_tree_path ${results}/../vocab_tree_flickr100K_words32K.bin \
  --SiftMatching.use_gpu 0
mkdir ${results}/${dset}/sparse
${colmap} \
  mapper \
  --database_path ${results}/${dset}/database.db \
  --image_path ${datasets}/${dset}/ \
  --export_path ${results}/${dset}/sparse/

```

I tried both `exhaustive_matcher` and `vocab_tree_matcher` but none of them worked on the books or the street scene. Right now the difference should only be SIFTGPU vs SIFTCPU...

**Comment by rajkataria** [comment]
Hi Lixin,

Let's hop on a zoom call (when you're free so we can resolve this issue). What time and email do you want me to send the invite to?

I'm on EST, so am available from now to 6PM.

Thanks,
Raj

**Comment by lxxue** [comment]
Hi Raj,

Thank you for your time and it's so kind of you. I am also available from now to 6PM EST. My email is . 

Best,
Lixin

**Comment by lxxue** [comment]
The problem is resolved. Adding a '/` in the script would solve the problem lol. The result looks perfect!

```
dset=street                                                    # if no slash in dset
${colmap} \
  mapper \
  --database_path ${results}/${dset}//database.db \            # then we need double slash here
  --image_path ${datasets}/${dset}/ \
  --export_path ${results}/${dset}/sparse/
```
